// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://tnbogilipykpodiqztjn.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuYm9naWxpcHlrcG9kaXF6dGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMwMzg1ODUsImV4cCI6MjA0ODYxNDU4NX0.nXpXvZIERDFlwpsI6eJY0-YZt83Coer9AiQOEwXxHrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);